name: environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - r-base=4.2.3
  - plotly
  - os
  - anndata
  - scanpy
  - seaborn
  - metacells
  - pandas
  - matplotlib
  - scikit-learn
  - numpy
  - r-tidyverse
  - r-dplyr
  - r-ggplot2 
  - r-reshape2
  - r-plotly 
  - r-stringr
